version: "3.8"
services:
  app:
    container_name: syntrade-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: syntrade-backend
    depends_on:
      - postgres
      - redis
      - flask
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - "./app:/usr/src/app"
    command: npm run dev
  postgres:
    container_name: syntrade-database
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    container_name: syntrade-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis:/data
  flask:
    container_name: syntrade-pricing
    build:
      context: .
      dockerfile: Dockerfile.pricing.dev
    image: syntrade-pricing
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - "./pricing:/usr/src/pricing"
volumes:
  app:
  postgres:
  redis:
  flask:
